### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by GaikwadPratik** [aironavt/node-linux-pam#3]

**Comment by GaikwadPratik** [comment]
@aironavt ,

Thank you for merging the PR. When are you planning to release it next?

**Comment by aironavt** [comment]
In the next 1-2 weeks.

**Comment by aironavt** [comment]
@GaikwadPratik released. Fixes are in 0.2.1

**Comment by GaikwadPratik** [comment]
Thank you @aironavt
