### ISSUE TITLE
Compilation issue on macos

### ISSUE THREAD

**Issue by GaikwadPratik** [aironavt/node-linux-pam#5]
Compilation fails on OSX because of configuration for `node-gyp`

**Comment by aironavt** [comment]
Hi!

The package was supposed to be used only for linux.

did you manage to build a package for OSX and use it for authentification?

**Comment by GaikwadPratik** [comment]
no, this PR allows anyone to add it do actual dependency instead of as optional dependency. It was just meant to allow them to compile on MacOS but it won't be usable on MacOS

**Comment by GaikwadPratik** [comment]
Since this package cannot be used on MacOS anyway, I'll just close this issue and associated PR.
